### PR TITLE
Add ubuntu server bypass error case for invalid registry urls

### PR DESCRIPTION
**Pull request by michael-valdron**
### What does this PR do?:

Adds a bypass error case to expect `Get "http://http//invalid.com/devfiles/notexist/": dial tcp: lookup http on 127.0.0.53:53: server misbehaving` for invalid registry urls in Ubuntu Server instances, which are the instances known to give this error for invalid urls when using `Go 1.21`.

### Which issue(s) this PR fixes:

fixes devfile/api#1588

### PR acceptance criteria:
Testing and documentation do not need to be complete in order for this PR to be approved. We just need to ensure tracking issues are opened and linked to this PR, if they are not in the PR scope due to various constraints.

- [X] Unit/Functional tests

  

- [X] [QE Integration test](https://github.com/devfile/integration-tests) 

  

- [ ] Documentation (READMEs, Product Docs, Blogs, Education Modules, etc.)

   

- [ ] Client Impact

  

- [x] Gosec scans
  

### How to test changes / Special notes to the reviewer:

Use `Go 1.21.10` under an [Ubuntu Server 22.04 LTS](https://releases.ubuntu.com/22.04/ubuntu-22.04.4-live-server-amd64.iso) instances and run:

```
make test
```

### CODE REVIEW

**Comment by michael-valdron** [comment]
> Documentation (READMEs, Product Docs, Blogs, Education Modules, etc.)
> Client Impact

N/A

**Comment by michael-valdron** [comment]
/hold

Need to amend error pattern for compatibility with expected errors, in the event this is fixed.

**Review by thepetk — APPROVED** [review]
/lgtm

**Pull request merged**
