### PR TITLE
Fix parent version on test devfile

### PR DESCRIPTION
**Pull request by thepetk**
### What does this PR do?:
The `Test_Parent_RegistryURL.yaml` consumes the latest parent version of `nodejs`. As a result any breaking changes will impact the library's tests. This PR simply fixes the version to `2.2.1` (current latest) so the test related to this file remain unimpacted by any changes of the `devfile/registry)

### Which issue(s) this PR fixes:

N/A

### PR acceptance criteria:
Testing and documentation do not need to be complete in order for this PR to be approved. We just need to ensure tracking issues are opened and linked to this PR, if they are not in the PR scope due to various constraints.

- [ ] Unit/Functional tests

  

- [ ] [QE Integration test](https://github.com/devfile/integration-tests) 

  

- [ ] Documentation (READMEs, Product Docs, Blogs, Education Modules, etc.)

   

- [ ] Client Impact

  

- [ ] Gosec scans

### CODE REVIEW

**Review by Jdubrick — COMMENTED** [review]
This looks like it is reverting changes made [here](https://github.com/devfile/library/pull/213). Do we need to change the other items in that PR as well?

**Comment by thepetk** [comment]
> This looks like it is reverting changes made [here](https://github.com/devfile/library/pull/213). Do we need to change the other items in that PR as well?

No I don't think so, I didn't notice this change. I think the PR I'm mentioning needs to be rebased instead.

**Comment by thepetk** [comment]
> > This looks like it is reverting changes made [here](https://github.com/devfile/library/pull/213). Do we need to change the other items in that PR as well?
> 
> No I don't think so, I didn't notice this change. I think the PR I'm mentioning needs to be rebased instead.

@Jdubrick although I think might worth pin the `parent` version to `2.2.1` so we don't have the same issue again when someone updates the nodejs schemaversion.

cc: @michael-valdron

**Comment by Jdubrick** [comment]
2.2.1 sounds good to me. I think we should open an issue for overhauling the tests so we can properly test 2.2.2 schemas, wdyt? @thepetk

**Comment by thepetk** [comment]
> 2.2.1 sounds good to me. I think we should open an issue for overhauling the tests so we can properly test 2.2.2 schemas, wdyt? @thepetk

Yeah I didn't open something cause @michael-valdron has the intention to bring it up as a discussion topic. If needed I'll create one afterwards :)

**Review by Jdubrick — APPROVED** [review]
/lgtm

**Pull request merged**
