### PR TITLE
bump k8s api

### PR DESCRIPTION
**Pull request by Kartikey-star**
This PR is aimed at making the changes required for https://github.com/openshift/console/pull/13816.

The PR to bump the k8s api in devfile api is merged https://github.com/devfile/api/pull/1545/.
The current PR makes the required changes for library.

fixes https://github.com/devfile/api/issues/1543

### CODE REVIEW

**Comment by michael-valdron** [comment]
fixes https://github.com/devfile/api/issues/1543

**Comment by michael-valdron** [comment]
@Kartikey-star CI check seems to fail on `Test_parseFromRegistry/should_fail_if_registryUrl_is_invalid`.

Tried reproducing locally in debug mode as well with no luck:

```
"Get \"http://http//invalid.com/devfiles/notexist/\": dial tcp: lookup http: no such host" matches "Get .* dial tcp: lookup http: .*"
```

Also, retried CI check and it still fails, from what I can tell the CI check error is different:

```
"Get "http://http//invalid.com/devfiles/notexist/": dial tcp: lookup http on 127.0.0.53:53: server misbehaving"
```

We can open a issue to investigate this.

**Comment by michael-valdron** [comment]
> We can open a issue to investigate this.

devfile/api#1588

FYI @Kartikey-star

**Comment by thepetk** [comment]
@Kartikey-star could you rebase your PR with the latest changes of the library repo?

**Comment by michael-valdron** [comment]
fix for failure coming with #217 

FYI @Kartikey-star

**Comment by michael-valdron** [comment]
> fix for failure coming with #217
> 
> FYI @Kartikey-star

@Kartikey-star Changes are merged, rebase your changes again and the check should pass now.

**Review by thepetk — APPROVED** [review]
/lgtm

**Pull request merged**
